-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "commission" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "commissionRate" DOUBLE PRECISION NOT NULL DEFAULT 0.05,
ADD COLUMN     "sellerEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Seller" ADD COLUMN     "totalEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalCommissionPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "pendingBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
